[package]
name = "mjml"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "mjml"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
mrml = { version = "1.2.10", features = ["parse", "render", "orderedmap"] }
